--runAllPrivilegeTests.psql

--Andrew Figueroa, Steven Rollo
--Data Science & Systems Lab (DASSL)
--https://dassl.github.io/

--(C) 2017- DASSL. ALL RIGHTS RESERVED.
--Licensed to others under CC 4.0 BY-SA-NC
--https://creativecommons.org/licenses/by-nc-sa/4.0/

--PROVIDED AS IS. NO WARRANTIES EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.

--This psql script executes all of the privilege tests, pausing before each of
-- the two sets: The first where all statements should succeed, and other
-- where all statements should fail.


--We want to allow errors to occur in order to allow all tests that should fail
-- to be run, along with having the cleanup process complete
\set ON_ERROR_STOP off
--DEV: On error - run cleanup?

--Remember the current user so we can switch back at the end
-- Currently, this is assuming the starting superuser account is 'postgres'
-- you must change this if you want to switch back to a different superuser account
-- at the end of the script
\set psqlCurrentUser postgres
--DEV: Use USER
--DEV: Use stored password


\echo 'The following tests should complete without any errors'
\prompt 'Press enter to continue...' unusedInputVariable

\ir 0_setup.sql

\connect - ptins0
\ir 1_instructorPass.sql

\connect - ptstu0
\ir 2_studentPass.sql

\connect - ptdbm0
\ir 3_dbmanagerPass.sql

\connect - ptins1
\ir 4_instructorPass2.sql

\echo 'README: If any previous test resulted in a warning, error, or exception, then privilege tests have failed'
\echo 'All of the following tests should result in errors'
\prompt 'Press enter to continue...' unusedInputVariable

\ir 5_instructorFail.sql

\connect - ptstu1
\ir 6_studentFail.sql

\connect - ptdbm1
\ir 7_dbmanagerFail.sql

\echo 'Initiating cleanup'
\prompt 'Press enter to continue...' unusedInputVariable

\connect - :psqlCurrentUser
\ir 8_cleanup.sql