--runAllPrivilegeTests.psql

--Andrew Figueroa, Steven Rollo
--Data Science & Systems Lab (DASSL)
--https://dassl.github.io/

--(C) 2017- DASSL. ALL RIGHTS RESERVED.
--Licensed to others under CC 4.0 BY-SA-NC
--https://creativecommons.org/licenses/by-nc-sa/4.0/

--PROVIDED AS IS. NO WARRANTIES EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.

--This psql script executes all of the privilege tests, pausing before each of
-- the two sets: The first where all statements should succeed, and other
-- where all statements should fail.


--We want to allow errors to occur in order to allow all tests that should fail
-- to be run, along with having the cleanup process complete
\set ON_ERROR_STOP off

--Stores the original user the original executing user from psql's :USER
-- environment variable
\set POSTGRES_USER :USER


\echo 'The following tests should complete without any errors'
\prompt 'Press enter to continue...' unusedInputVariable

\ir 0_setup.sql

--PGPASSWORD environment variable allows auto-login using the set password
\setenv PGPASSWORD ptins0
\connect - ptins0
\ir 1_instructorPass.sql

\setenv PGPASSWORD ptstu0
\connect - ptstu0
\ir 2_studentPass.sql

\setenv PGPASSWORD ptdbm0
\connect - ptdbm0
\ir 3_dbmanagerPass.sql

\setenv PGPASSWORD ptins1
\connect - ptins1
\ir 4_instructorPass2.sql

\echo 'README: If any previous test resulted in a warning, error, or exception, then privilege tests have failed'
\echo 'All of the following tests should result in errors'
\prompt 'Press enter to continue...' unusedInputVariable

\ir 5_instructorFail.sql

\setenv PGPASSWORD ptstu1
\connect - ptstu1
\ir 6_studentFail.sql

\setenv PGPASSWORD ptdbm1
\connect - ptdbm1
\ir 7_dbmanagerFail.sql

\echo 'Initiating cleanup'
\prompt 'Press enter to continue...' unusedInputVariable

--Reset stored password to allow user to log in with original role
\setenv PGPASSWORD
\connect - :POSTGRES_USER
\ir 8_cleanup.sql