--testAddLogMgmt.sql - ClassDB

--Andrew Figueroa, Steven Rollo, Sean Murthy
--Data Science & Systems Lab (DASSL)
--https://dassl.github.io

--(C) 2017- DASSL. ALL RIGHTS RESERVED.
--Licensed to others under CC 4.0 BY-SA-NC
--https://creativecommons.org/licenses/by-nc-sa/4.0/

--PROVIDED AS IS. NO WARRANTIES EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.


--The following test script should be run as a superuser, otherwise tests will fail

--This script uses psql's \c command to change connections. You will have to
-- input the password for each role manually during the switch

--The following tests are performed. An error code of ERROR X.Y indicates that test
-- y in section x failed

--A) Checks as instructor

\set ON_ERROR_STOP on

--Remember the current user so we can switch back at the end
\set psqlCurrentUser SELECT CURRENT_USER

SET SESSION client_min_messages TO WARNING;

--Tests for superuser privilege on current_user
DO
$$
BEGIN
   IF NOT classdb.isSuperUser() THEN
      RAISE EXCEPTION 'Insufficient privileges: script must be run as a superuser';
   END IF;
END
$$;

DO
$$
BEGIN
   --Create users to test connection logging
   PERFORM ClassDB.createStudent('conStudent01', 'con test student 01', NULL, NULL, TRUE, TRUE, ' ');
   PERFORM ClassDB.createStudent('conStudent02', 'con test student 02', NULL, NULL, TRUE, TRUE, ' ');
   PERFORM ClassDB.createInstructor('conInstructor01', 'con test instructor 01', NULL, NULL, TRUE, TRUE, ' ');
   PERFORM ClassDB.createDBManager('conDBManager01', 'con test db manager 01', NULL, NULL, TRUE, TRUE, ' ');

   --Fill up the log with any existing connections
   PERFORM ClassDB.importLog();
END;
$$;

--Switch to different user to get some conenction in the log
\c  - constudent01

\c - constudent02

\c - condbmanager01

\c - coninstructor01

\c - :psqlCurrentUser

--Check the logs
DO
$$
DECLARE
   initialLogSize INT;
   newLogSize INT;
BEGIN
   --Get the initial size of the connection log
   SELECT COUNT(*)
   INTO initialLogSize
   FROM ClassDB.ConnectionActivity;

   PERFORM ClassDB.importLog();

   SELECT COUNT(*)
   INTO newLogSize
   FROM ClassDB.ConnectionActivity;

   --Check if the number of new connections in the log equals the number of connections
   -- we made in the test
   IF newLogSize - initialLogSize <> 4 THEN
      RAISE EXCEPTION 'ERROR CODE A.1';
   END IF;

   --Drop users & related objects
   PERFORM ClassDB.dropStudent('conStudent01', true);
   PERFORM ClassDB.dropStudent('conStudent02', true);
   PERFORM ClassDB.dropInstructor('conInstructor01', true);
   PERFORM ClassDB.dropDBManager('conDBManager01', true);

   DROP SCHEMA conStudent01 CASCADE;
   DROP SCHEMA conStudent02 CASCADE;
   DROP SCHEMA conInstructor01 CASCADE;
   DROP SCHEMA conDBManager01 CASCADE;

   RAISE NOTICE 'Success!';
END;
$$;
