--testAddLogMgmt.sql - ClassDB

--Andrew Figueroa, Steven Rollo, Sean Murthy
--Data Science & Systems Lab (DASSL)
--https://dassl.github.io

--(C) 2017- DASSL. ALL RIGHTS RESERVED.
--Licensed to others under CC 4.0 BY-SA-NC
--https://creativecommons.org/licenses/by-nc-sa/4.0/

--PROVIDED AS IS. NO WARRANTIES EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.


--The following test script should be run as a superuser, otherwise tests will fail

--***WARNING*** - This script truncates ClassDB.ConnectionActivity

--This script uses psql's \c command to change connections. You will have to
-- input the password for each role manually during the switch

--The following tests are performed. An error code of ERROR X.Y indicates that test
-- y in section x failed

--A) Checks as instructor

\set ON_ERROR_STOP on

SET SESSION client_min_messages TO WARNING;

--Tests for superuser privilege on current_user
DO
$$
BEGIN
   IF NOT classdb.isSuperUser() THEN
      RAISE EXCEPTION 'Insufficient privileges: script must be run as a superuser';
   END IF;
END
$$;

DO
$$
BEGIN
   --Clear the DDL Activity log
   TRUNCATE ClassDB.ConnectionActivity;

   --Create users to test connection logging
   PERFORM ClassDB.createStudent('conStudent01', 'con test student 01');
   PERFORM ClassDB.createStudent('conStudent02', 'con test student 02');
   PERFORM ClassDB.createInstructor('conInstructor01', 'con test instructor 01');
   PERFORM ClassDB.createDBManager('conDBManager01', 'con test db manager 01');
END;
$$;

--Switch to different user to get some conenction in the log
\c  - constudent01

\c - constudent02

\c - condbmanager01

\c - coninstructor01

--Check the logs
DO
$$
BEGIN
   PERFORM ClassDB.importLog();
   --There's no easy way to stop older connection from being imported in a script,
   -- so I am temporarily just check for a minimum of 4 connections found
   IF (SELECT COUNT(*) FROM ClassDB.ConnectionActivity) >= 4 THEN
      RAISE EXCEPTION 'ERROR CODE A.1';
   END IF;

   --Drop users & related objects
   --Currently broken
   --PERFORM ClassDB.dropStudent('conStudent01', true);
   --PERFORM ClassDB.dropStudent('conStudent02', true);
   --PERFORM ClassDB.dropInstructor('conInstructor01', true);
   --PERFORM ClassDB.dropDBManager('conDBManager01', true);

   RAISE NOTICE 'Success!';


END;
$$;
